### PR TITLE
Isotropic Resampling

### PR DESCRIPTION
**Pull request by Besler**
Implements isotropic resampling.

### CODE REVIEW

**Comment by Besler** [comment]
@asmichalski Do you want to quickly check that what I'm doing here makes sense? No reason to download and test.

It's the following:
- We want to resample to an isotropic resolution, say 1.0 mm x 1.0 mm x 1.0 mm
- First, we avoid aliasing. If spacing in direction i is less than the resolution, blur with a Gaussian.
- Perform BSpline interpolation onto the isotropic grid.

**Comment by asmichalski** [comment]
@Besler Yes. Your resampling process makes sense.

**Comment by asmichalski** [comment]
To avoid aliasing, you want to blur if the image spacing is greater than the isotropic voxel size. Right? If we sample to 1 mm isotropic and the slice interval is 1.25 mm, then blurring is performed. Whereas if in plane size is 0.625 mm and we resample to 1 mm, no blurring is required.

**Comment by Besler** [comment]
It's exactly the opposite! If the spacing is 0.1 mm and you want 1.0 mm, you need to blur. If you're going from 2.0 mm to 1.0 mm, you don't need to blur. I don't speak so good so I think I presented backwards above.

Anyways, going to merge here.

**Pull request merged**
